myblog/blog/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name='blog'

urlpatterns = [
    path('',welcome,name='welcome'),
    path('signup',signup_view,name='signup'),
    path('login',login_view,name='login'),
    path('home',home,name='home'),
    path('logout',logout_view,name='logout'),
    path('option1',option_1,name='option1'),
     path('myview',my_view,name='myview'),


]

myblog/myblog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
]

myblog/blog/models.py
from django.db import models

myblog/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _

class SignUpForm(UserCreationForm):
 password1 = forms.CharField(label='Password', widget=forms.PasswordInput())
 password2 = forms.CharField(label='Confirm Password (again)', widget=forms.PasswordInput())
 class Meta:
  model = User
  fields = ['username', 'first_name', 'last_name', 'email']
  labels = {'first_name': 'First Name', 'last_name': 'Last Name', 'email': 'Email'}
  widgets = {'username':forms.TextInput(),
  'first_name':forms.TextInput(),
  'last_name':forms.TextInput(),
  'email':forms.EmailInput(),
  }

class LoginForm(AuthenticationForm):
 username = UsernameField(widget=forms.TextInput())
 password = forms.CharField(label=_("Password"), strip=False, widget=forms.PasswordInput())

myblog/blog/views.py
from django.shortcuts import render,redirect
from django.http import *
from django.contrib.auth import *
from django.contrib import messages
from django.contrib.auth.models import *
from django.contrib.auth.forms import *
from .forms import *
import cv2

def welcome(request):
     return render(request,'welcome.html',)
def signup_view(request):
    if request.method == "POST":
       form = SignUpForm(request.POST)
       if form.is_valid():
          messages.success(request, 'Congratulations!! You have become an Author.')
          user = form.save()
    else:
       form = SignUpForm()
    return render(request, 'signup.html', {'form':form})
def login_view(request):
   if request.method == "POST":
         form = LoginForm(request=request, data=request.POST)
         if form.is_valid():
          uname = form.cleaned_data['username']
          upass = form.cleaned_data['password']
          user = authenticate(username=uname, password=upass)
          if user is not None:
            login(request, user)
            return redirect('/blog/home')
   else:
      form = LoginForm()
   return render(request, 'login.html', {'form':form})

def home(request):
 if request.user.is_authenticated:
  user = request.user
  full_name = user.get_full_name()
  return render(request, 'home.html', {'full_name':full_name})
 else:
  return redirect('/blog/login')

def option_1(request):
    cam = cv2.VideoCapture(0)
    while cam.isOpened():
       ret, frame1 = cam.read()
       if cv2.waitKey(10) == ord('q'):
          break
    cv2.imshow('Granny Cam', frame1)
    return HttpResponse("")

def my_view(request):
    # Your integration logic here
    result = option_1(request)  # Call your Python function or code here

    return HttpResponse(result)


def logout_view(request):
    logout(request)
    return redirect('/blog/login')

myblog/blog/templates/home.html
{% extends 'main.html' %}
{% block content %}
<h2>welcome {{full_name}}</h2>
<h1>This Is A Home Page</h1>
<ul>
    <a href="{% url 'blog:myview'%}"><li>option 1</li></a>
    <a href="{% url 'blog:home'%}"><li>option 2</li></a>
    <a href="{% url 'blog:home'%}"><li>option 3</li></a>
    <a href="{% url 'blog:home'%}"><li>option 4</li></a>
</ul>
{% endblock%}

myblog/blog/templates/login.html
{% extends 'main.html' %}
{% block content %}
<div>
 <h3>Login Page</h3> 
 <form action="" method="post" novalidate>
   {% csrf_token %}
   {% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
     <p >invalid username or password</p>
    {% endfor %}
   {% endif %}
   {% for fm in form %}
    <div class="form-group">
    {{fm.label_tag}} {{fm}} <small>{{fm.errors|striptags}}</small>
    <br><br>
    </div>
   {% endfor %}
   <input type="submit"  value="Login">
   <input type="reset" value="clear">
  </form>
</div>

{% endblock content %}

myblog/blog/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>MyBlog</h1>
    {% include 'navbar.html' %}
    {% block content%}
    {% endblock %}
</body>
</html>

myblog/blog/templates/navbar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<style>
    .nav a
    {
        margin-left: 2%;
    }
</style>
<body>
    <div class="nav">
        <a href="{% url 'blog:home'%}">home</a>
        <a href="{% url 'blog:logout'%}">logout</a>
        <a href="{% url 'blog:welcome'%}">welcome</a>
        <a href="{% url 'blog:signup'%}">signup</a>
        <a href="{% url 'blog:login'%}">login</a>
    </div>
</body>
</html>

myblog/blog/templates/option1.html
{% extends 'main.html' %}
{% block content %}
<h2>welcome {{full_name}}</h2>
<h1>This Is ANn Option 1</h1>
<h3>Enter Q To Exit</h3>
{% endblock%}

myblog/blog/templates/signup.html
{% extends 'main.html' %}
{% block content %}

<div>
 <h3>Become an Author</h3> 
 {% if messages %}
 {% for message in messages %}
  <p>{{message}}</p>
 {% endfor %}
 {% endif %}
 <form action="" method="post" novalidate>
  {% csrf_token %}
  {% for fm in form %}
   <div>
   {{fm.label_tag}} {{fm}} <small>{{fm.errors|striptags}}</small>
   <br><br>
   </div>
  {% endfor %}
  <input type="submit" value="Submit">
  <input type="reset" value="clear">
  {% if form.non_field_errors %}
   {% for error in form.non_field_errors %}
    <p>{{error}}</p>
   {% endfor %}
  {% endif %}
 </form>
</div>

{% endblock content %}

myblog/blog/templates/welcome.html
{% extends 'main.html' %}
{% block content %}
<br><br>
<h1>welcome To This Security System Camera</h1>
{% endblock %}